version: '3'
services:
  challenge:
    build: ./service
    ports:
      - "8505:8080"
    links:
      - redis
    environment:
      - UWSGI_INI=/app/uwsgi.ini
      - LISTEN_PORT=8080
      - FLAG=nek0pts{nek0chan}
      - RANDOM=REDACTED
    restart: always
  report:
    build: ./report
    ports:
      - "1337:8080"
    links:
      - redis
      - crawler
    environment:
      - UWSGI_INI=/app/uwsgi.ini
      - LISTEN_PORT=8080
    restart: always

  crawler:
    build: ./crawler
    links:
      - challenge
      - redis
    restart: always

  redis:
    build: ./redis
    restart: always
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.1/16
