[tool.poetry]
name = "worker"
version = "0.1.0"
description = ""
authors = ["BitK"]

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.1.1"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
